### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by qqibrow** [qqibrow/SimpleTodo#1]
my app is complete, please review! Thank you! @codepathreview @codepath @thecodepath @nesquena

**Comment by nesquena** [comment]
What's your full name so I can match you?

**Comment by qqibrow** [comment]
My full Name is Lu Niu and my email is lniu@yahoo-inc.com. Thank you!

**Comment by nesquena** [comment]
Thanks. Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program starts.

Nice job with the project, hope you found it as a helpful introduction and see you on Tuesday!
